In [22]:
# Creating Arrays

import numpy as np
vector_row=np.array([1,2,3])
vector_column=np.array([[1],[2],[3]])
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.dtype.name)
print(len(matrix))
zer_3=np.zeros(3)
print(zer_3)
zer_2_3=np.zeros((2,3))
# similarly we have np.ones()

# Create a 2X2 identity matrix
f = np.eye(2)
# Create an array of evenly
# spaced values
l=np.linspace(0,2,9)
print(l)
arang=np.arange(0,10,3)
print(arang)


np.random.random((2,2)) #Create an array with random values
np.empty((3,2))#Create an empty array

[[1 2 3]
 [4 5 6]]
int32
2
[0. 0. 0.]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0 3 6 9]


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Inspecting Your Array

 a.shape       #Array dimensions
    
 len(a)        #Length of array

 b.ndim        #Number of array dimensions
    
 e.size        #Number of array elements

 b.dtype       #Data type of array elements

 b.astype(int) #Convert an array to a different type

In [ ]:
# OPerations
a+b
a-b
a/b
a*b
# we have methods too for the same

np.exp(b) #Exponentiation
>>> np.sqrt(b)# Square root
>>> np.sin(a) #Print sines of an array
>>> np.cos(b) #Element-wise cosine
>>> np.log(a) #Element-wise natural logarithm
>>> e.dot(f) #Dot product



a.sum() Array-wise sum
>>> a.min() Array-wise minimum value
>>> b.max(axis=0) Maximum value of an array row
>>> b.cumsum(axis=1) Cumulative sum of the elements
>>> a.mean() Mean
>>> b.median() Median
>>> a.corrcoef() Correlation coefficient
>>> np.std(b) Standard deviation


np.copy(a) #Create a copy of the array
a.sort() #Sort an array

In [36]:
# Subsetting,Slicing and indexing
num=32
print(num)
print(type(num))
matrix=np.array([[1,2,3],[4,5,6]])
h= matrix[1,1]
print(h)
print(type(h))
i=matrix[0:2]#jmutliple rows
print(i)
print(type(i))
print(matrix[:,0:2])
print(type(matrix[:,0:2]))


# Boolean Indexing
a[a<2] #Select elements from a less than 2

32
<class 'int'>
5
<class 'numpy.int32'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[1 2]
 [4 5]]
<class 'numpy.ndarray'>


In [37]:
# Array manipulation

# Changing Shape
g.reshape(3,-2) #Reshape, but don’t change data
h.resize((2,6)) #Return a new array with shape (2,6)
arr1_2d.flatten()
# Adding data
np.append([1, 2, 3], [4, 5, 6,7, 8, 9])
>>>array([1, 2, 3, ..., 7, 8, 9])
np.insert(a, 1, 5)# Insert 5 in  array at 1th index



n=arrange(0,12)


NameError: name 'g' is not defined

In [60]:
# 2-d Numpy array
n=np.arange(0,12)
print(n)
new=n.reshape(3,4)
print(new)
# np.append(new,[12,13,14]) #Not giving axis will flatten out the array
# np.append(new,[[12,13,14,15]],axis=0)#this will add another row
# np.append(new,[[12],[13],[14]],axis=1)#This will add another column

# np.insert(new,posn,value,axis)

np.insert(new,[1,2],100)#not specifying axis will result in flattening
np.insert(new,(1,2),[100,200,300,400],axis=0)# 1 AND 2 row are updated with the list

# DELETION
np.delete(array,value) #Delete items from an array
np.delete(new,2)

# STACKING
np.vstack((a,b)) #Stack arrays vertically (row-wise)
np.hstack((e,f))  #Stack arrays horizontally (column-wise)
# SPLIT
np.hsplit(a,3) #Split the array horizontally at the 3rd
np.vsplit(c,2) #Split the array vertically at the 2nd index
np.vsplit(new,3)


# GENERAL OBSVN THAT COMBINING ,SPLITTING ,ARITHMETIC OPNS,STATS  INVOLVES NP.()

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[  0,   1,   2,   3],
       [100, 200, 300, 400],
       [  4,   5,   6,   7],
       [100, 200, 300, 400],
       [  8,   9,  10,  11]])

In [68]:
# SOME OTHER IMPORTANT POINTS
bmi > 21 and bmi < 22
# bmi is a numpy array
>>>This will generate an error
>>>You can't compare two boolean arrays

np.logical_and(bmi > 21, bmi < 22)

# np.logical_or() and np.logical_not()

# ITERATION
# USINGN ndarray.flatten( )
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7]) 
meas = np.array([np_height, np_weight])
for val in np.nditer(meas) : 
    print(val)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])